#include "olectl.h"
import "oaidl.idl";
import "ocidl.idl";

// TODO: generate other uuids

[
	uuid(d66ad502-5443-4b3f-93e4-ec0975fd3408),
	version(1.0),
	helpstring("ActiveN.Samples.WebView2 1.0 Type Library")
]
library ActiveNSamplesWebView2Lib
{
	importlib("stdole2.tlb");

	[
		object,
		uuid(9d51ea97-30dd-4e70-99ae-a5085fbf8095),
		dual,
		nonextensible,
		pointer_default(unique),
		helpstring("IWebView2Control Interface"),
	]
	interface IWebView2Control : IDispatch
	{
		[propput]
		HRESULT Source([in] BSTR value);
		[propget]
			HRESULT Source([out, retval]BSTR* value);

		[propget]
			HRESULT StatusBarText([out, retval]BSTR* value);

		[propget, id(DISPID_CAPTION)]
			HRESULT DocumentTitle([out, retval]BSTR* value);

		[propget]
			HRESULT BrowserVersion([out, retval]BSTR* value);

		HRESULT Navigate(BSTR uri);
		HRESULT NavigateToString(BSTR htmlContent);
		HRESULT GoBack();
		HRESULT GoForward();

		[id(DISPID_REFRESH)]
			HRESULT Reload();
	};

	[
		uuid(2c3aaa0e-573f-45c2-932d-c9fd3cbacf1a),
		helpstring("Event interface for IWebView2Control")
	]
		dispinterface IWebView2ControlEvents
	{
		properties:
		methods:
			// ids here *must* match those in WebView2ControlEventsDispIds.cs
			[id(100)]
			void NavigationCompleted();

			[id(101)]
			void FrameNavigationCompleted();

			[id(102)]
			void NewWindowRequested();

			[id(103)]
			void DocumentTitleChanged();
	};

	[
		uuid(27ef2dff-595f-4724-aea1-d16f7730dc33),
		helpstring("WebView2Control Class")
	]
		coclass WebView2Control
	{
		[default] interface IWebView2Control;
	}
}