import "oaidl.idl";
import "ocidl.idl";

[
	object,
	oleautomation,
	uuid(00000002-2126-40c8-a2f3-8fa83f8cc1f6)
]
interface IHelloWorldControl : IDispatch
{
	HRESULT ComputePi([out, retval] double* ret);
};

[
	uuid(00000000-2126-40c8-a2f3-8fa83f8cc1f6),
	version(1.0),
	helpstring("ActiveN.Samples.HelloWorld 1.0 Type Library")
]

library ActiveNSamplesHelloWorldLib
{
	importlib("stdole2.tlb");

	[
		uuid(00000001-2126-40c8-a2f3-8fa83f8cc1f6)
	]
		coclass HelloWorldControl
	{
		[default] interface IHelloWorldControl;
	}
}